### ISSUE TITLE
[1.20.1] Invisibility not visibly affecting non-player entities

### ISSUE THREAD

**Issue by IstasNix** [Mithion/Mana-And-Artifice#696] opened 2024-02-08 03:19 UTC
**Describe the bug**
Invisibility does not (visibly) affect any non-player entities. Players do seem to be affected properly. I believe it is only a visual/rendering issue, since the wandering trader that first lead me to discover this was not mobbed by hostiles and acted as if he were still invisible.

**To Reproduce**
1. Get an invisibility spell or potion.
2. Use on self, it works.
3. Use on other non-player targets, it does not.
4. See screenshot, I am invisible but those chickens are not. Does not work on other mobs, either.

**Expected behavior**
Affected entities should no longer be visible, just particles (or nothing if source would hide particles).

**Screenshots**
![MNAInvisNotWork](https://github.com/Mithion/Mana-And-Artifice/assets/20792963/17d6f48a-ebfa-4c82-bb3c-9081b7f6bd4a)

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.6 / 3.0.0.7
 - Forge Version: 1.20.1-47.1.88

**Additional context**
First discovered in a modpack environment, but it happens even with only MNA and prereqs.

**Comment by Mithion** [comment] 2024-02-08 17:15
Hey, thanks for the report!  This is a duplicate of #681.  I'll be tracking the progress there.

**Closed by Mithion** 2024-02-08 17:15 UTC
