### ISSUE TITLE
Can't Use JEI/REI Cause your Mod Crash us to Desktop when we search anything

### ISSUE THREAD

**Issue by ModernGamingWorld** [Mithion/Mana-And-Artifice#433] opened 2022-02-06 19:06 UTC
**Describe the bug**
Description: Getting tooltips

net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: mna:mna:manaweave_patterns/inverted_split_triangle
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:37) ~[client-1.18.1-20211210.034407-srg.jar%23315!/:?] {re:mixin,re:classloading,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:rhino-common.mixins.json:ResourceLocationMixin,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:46) ~[client-1.18.1-20211210.034407-srg.jar%23315!/:?] {re:mixin,re:classloading,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:rhino-common.mixins.json:ResourceLocationMixin,pl:mixin:A,pl:epic_rei_lmao:A}
	at mezz.jei.api.ingredients.IIngredientHelper.getResourceLocation(IIngredientHelper.java:108) ~[RoughlyEnoughItems-7.2.425.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at mezz.jei.api.ingredients.IIngredientHelper.getDisplayModId(IIngredientHelper.java:81) ~[RoughlyEnoughItems-7.2.425.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.jeicompat.wrap.JEIEntryDefinition.getContainingNamespace(JEIEntryDefinition.java:95) ~[RoughlyEnoughItems-7.2.425.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getContainingNamespace(AbstractEntryStack.java:134) ~[RoughlyEnoughItems-7.2.425.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:214) ~[RoughlyEnoughItems-7.2.425.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:85) ~[RoughlyEnoughItems-7.2.425.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:74) ~[RoughlyEnoughItems-7.2.425.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:44) ~[RoughlyEnoughItems-7.2.425.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:217) ~[RoughlyEnoughItems-7.2.425.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:202) ~[RoughlyEnoughItems-7.2.425.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:186) ~[RoughlyEnoughItems-7.2.425.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:61) ~[RoughlyEnoughItems-7.2.425.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:49) ~[RoughlyEnoughItems-7.2.425.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.matches(AsyncSearchManager.java:138) ~[RoughlyEnoughItems-7.2.425.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.lambda$get$3(AsyncSearchManager.java:106) ~[RoughlyEnoughItems-7.2.425.jar%23268!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames,pl:epic_rei_lmao:A}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames,pl:epic_rei_lmao:A}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**To Reproduce**
1. Launch my custom Modpack
2. Try to type something in REI in this instance
3. Game Freezes 
4. Crashes client straight to desktop

**Expected behavior**
Not to have a mod break or crash JEI/REI

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [latest 1.18.1]
 - Forge Version [39.0.66]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

[crash-2022-02-06_13.02.58-client.txt](https://github.com/Mithion/Mana-And-Artifice/files/8010998/crash-2022-02-06_13.02.58-client.txt)

**Comment by ModernGamingWorld** [comment] 2022-02-06 19:18
Updated, Had to fully remove your mod so I can use REI/JEI. Idk what's causing this, but even downgrading the version of the mod that it still crashes

**Comment by jank0cisco** [comment] 2022-02-08 07:38
i have also had the same issue

**Comment by ModernGamingWorld** [comment] 2022-02-12 01:20
@Mithion I cant test with JEI as I use REI in my 1.18 packs

**Comment by shedaniel** [comment] 2022-02-14 04:58
This is caused by Mana and Artifice, not REI. Ingredients should return the path of the resource in `getResourceId()`, Mana and Artifice is returning the entire ResLoc.

**Comment by ModernGamingWorld** [comment] 2022-02-14 05:02
Thanks Now @Mithion can fix this

**Comment by Mithion** [comment] 2022-05-04 14:20
This has been fixed in dev and will go out with the next release (1.18.1).

**Closed by Mithion** 2022-05-04 14:20 UTC
