### ISSUE TITLE
Crash when telling automatons to bind to lodestar. 

### ISSUE THREAD

**Issue by Wdrussell1** [Mithion/Mana-And-Artifice#123] opened 2021-01-14 05:25 UTC
I have made it through all 5 tiers of magic and wanted to automate the runes finally. I made an all diamond smart head bot. Gave the bot simple commands
Pick up > Put down item> scribe > take item > Place item
The game just locks up and crashes as soon as I bind to the lodestar.

https://pastebin.pl/view/800cbc13

**Comment by Mithion** [comment] 2021-01-15 02:00
This one I'm not sure about - I put something in that might fix this in 1.2.1.9, but I wasn't able to reproduce this issue, so not sure.
The issue seems to be related to the construct missing capabilities (carrying and smithing would be needed for that logic flow).

**Comment by Wdrussell1** [comment] 2021-01-15 05:59
Well, i also tried creating one that was just a simple MC chest, moving blank rune plates to another MC chest and it crashed as well.

**Comment by Mithion** [comment] 2021-03-13 18:25
Resolved in 1.3.0.4

**Closed by Mithion** 2021-03-13 18:25 UTC
Labels: bug
