### ISSUE TITLE
Some magic items work when discharged

### ISSUE THREAD

**Issue by aaronhowser1** [Mithion/Mana-And-Artifice#266] opened 2021-05-26 18:09 UTC
![image](https://user-images.githubusercontent.com/15698722/119709812-3e1aab00-be23-11eb-8ed4-add25130f2e4.png)

The elytra isn't discharging me at all
![image](https://user-images.githubusercontent.com/15698722/119709919-5ee30080-be23-11eb-9a97-d07f049dcc2d.png)

**Comment by Mithion** [comment] 2021-05-26 18:32
The elytra is intended to be able to become magic neutral.  Try setting your magic level to 30 or 40, it'll do it.
And even still, it's proving to "slow" your magic rengeration rate meaning you can't fight as well while flying.

**Comment by Mithion** [comment] 2021-06-23 04:14
The emberglow bracelet issue has been resolved in dev and will go out with 1.4.0.0.  The elytra functions as intended.

**Closed by Mithion** 2021-06-23 04:14 UTC
