### ISSUE TITLE
Projectile crash issue

### ISSUE THREAD

**Issue by skatingskelly** [Mithion/Mana-And-Artifice#792] opened 2024-05-15 08:07 UTC
**Describe the bug**
Projectiles not properly being disposed of clientside

**To Reproduce**
1. Cast any projectile spell
2. have any other player not look at the projectiles when they collide with something
3. repeat 100x
4. Crash via ticking entity error

**Expected behavior**
Projectiles get deleted properly, even if unrendered

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.14
 - NeoForge version 47.1.104

**Comment by Mithion** [comment] 2024-05-22 16:17
Crash mentioned, yet no crash report?

**Comment by ShelLuser** [comment] 2024-05-25 19:35
Apologies up front but.... not fully sober, and after I posted my last entry I couldn't help see this and well... while I share Mith's scepticism my friend Aya and me decided to follow up as a means of a silly _thank you_ for this **amazing** mod. 

We _went_ here:

![2024-05-25_15 51 46](https://github.com/Mithion/Mana-And-Artifice/assets/25201078/a10d6599-4850-4494-b278-351a22895bb5)

We made a deal: I gave Aya 2 projectile spells for free, the only caveat: she had to make it count, towards this issue obviously. So after she decided on the Crystalize spell I gave her 100 diamonds (see above) and she got to work while I stayed at the main area. And she gave it everything she got, even got caught up with a Hydra (offtopic story)...  

The results:

![2024-05-25_20 42 24](https://github.com/Mithion/Mana-And-Artifice/assets/25201078/265392a0-ea06-474c-8f74-f09256f2d8bc)

No, that's not 100, she actually did **way** _more_. She caught foxes, lizzards, bass...  the kind of (modded) entities which _will_ pick up on you going after 'm (even with other mods). No one hit wonders ;) We even learned that this spell also works underwater.

Aya's client didn't crash.

But there's more.. 

![2024-05-25_18 44 00](https://github.com/Mithion/Mana-And-Artifice/assets/25201078/b1797088-5d2e-48aa-8251-d5355f029cce)

Normally I'd have added a green box to emphasize but..  let's not and keep this vanilla: notice the Jade comment on top? She even caught the particle by accident, but this did _not_ crash anything.

![2024-05-25_21 31 18](https://github.com/Mithion/Mana-And-Artifice/assets/25201078/7b884dd8-a898-4f43-adc0-eb5d1e8d5cb3)

^ Time of writing. I'll let the pics speak for themselves.

OP: I am **not** claiming that nothing happened, but ... we can't reproduce, and believe me: we tried. My definition of a bug is simple: it needs to be reproducable.

**Comment by skatingskelly** [comment] 2024-05-26 21:24
> Crash mentioned, yet no crash report?

I'm very sorry but as it was on a public server and i wasn't the one crashing i had no crash report to give, I assumed it'd be reproduceable easily.
I have since gotten a screenshot of it and a crash report from one of the players online
[crash-2024-05-14_15.49.28-client.txt](https://github.com/Mithion/Mana-And-Artifice/files/15448983/crash-2024-05-14_15.49.28-client.txt)
![image](https://github.com/Mithion/Mana-And-Artifice/assets/40774977/bebcdc09-e9bf-4618-ae56-ee692e19d4cf)

**Comment by Mithion** [comment] 2024-06-12 21:10
This has been fixed in 3.0.0.15

**Closed by Mithion** 2024-06-12 21:10 UTC
Labels: bug, Fixed In Dev, 1.20
