### ISSUE TITLE
Tome of Recipes: Recipes with multiple ingredients broken

### ISSUE THREAD

**Issue by nanakisan** [Mithion/Mana-And-Artifice#1022] opened 2024-11-29 23:31 UTC
** Edited title to change focus from the transmutation recipe **

**Describe the bug**
Using the Tome of Recipes to set the 9 ingots of copper to quicksilver transmutation recipe breaks the required ingredients check."
If you have 1 ingot the bug doesn't work. But if you have at least 2 ingots of copper. You can run the 9 ingots transmutation as if you have 9 ingots of copper.

** Edit ** 
Just discovered that any recipe with multiple ingredients are affected by this interaction. All you need is 2 - 3 ingredients minimum after setting the recipe with the Tome does this happen. I have so far discovered this also happens with mana crystal fragments. The amount needed depends on the recipe.

**To Reproduce**
1. Do 9 ingot transmutation without Tome of Recipes
2. Save recipe to the Tome
3. Have Tome set and activate recipe
4. Use Tome on Manaweaving Altar
5. Recipe will work regardless of not having enough ingots

**Expected behavior**
Recipe should not work if you do not have the 9 ingots

**Screenshots**
![image](https://github.com/user-attachments/assets/1fd78511-a7bc-4f7f-abc4-341802933c1f)
![image](https://github.com/user-attachments/assets/6e446047-b501-43a3-8864-6a9070f5c0e1)
![image](https://github.com/user-attachments/assets/f432ffa3-34cd-4c17-aefc-2f8b2376ff4a)

I have confirmed that this is happening in base MnA with no additional mods
![image](https://github.com/user-attachments/assets/884e8d0a-c98c-4d9a-85de-7519b19bbfdf)
![image](https://github.com/user-attachments/assets/baaf88f2-55d1-4ebe-9e04-c1b6297ae841)

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1
 - Forge Version: 47.3.0

**Comment by ShelLuser** [comment] 2024-12-06 22:25
My friend Aya & me can fully reproduce the issue. We're using the exact same setup (including the same Forge version) and just to rule out possible causes I also asked her to remove any 'storage link items' (like the Occultism remote control) and it's just as you said...

In addition: Aya told me that there were two times when the book sharted glowing after copying the recipe but the recipe icon didn't appear in the radial menu. However... I couldn't reproduce that myself. Figured I'd still mention it just in case.

**Comment by Mithion** [comment] 2024-12-31 17:14
This was resolved in 3.1.0.2

**Closed by Mithion** 2024-12-31 17:14 UTC
Labels: Fixed In Dev
