### ISSUE TITLE
conflict with JEI rendering over 

### ISSUE THREAD

**Issue by SteamDoge9000** [Mithion/Mana-And-Artifice#343] opened 2021-10-16 03:40 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/38770780/137570747-7fd058fb-3d4a-4b48-be2a-9b4c3827e462.png)
Simple issue, the mod was not made to acomidate for JEI being in the way and for it to "Move" out of the way when its present instead of causing an overlap

**To Reproduce**
Not really possable, it will happen though if your gui is to where other elements will try to take up that space, the issue is that I cant click on the other tabs without jei being in the way and trigguring something else

**Expected behavior**

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.4.0.8]
 - Forge Version [e.g. 36.2.4]

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment] 2021-12-20 19:23
Closing as a duplicate of #245

**Closed by Mithion** 2021-12-20 19:23 UTC
Labels: Other Mod Issue

**Comment by SteamDoge9000** [comment] 2021-12-20 20:24
ah, hope that this gets fixed, it its any note, you can also do the same wtih ajusting its ui to change how JEI's will lay out as well, as it will instead cause the tabs in JEI to move out of the way of another UI instead of an overlap
