### ISSUE TITLE
Alex's caves rendering error

### ISSUE THREAD

**Issue by Fantomrat** [Mithion/Mana-And-Artifice#731] opened 2024-03-16 18:44 UTC
**Describe the bug**
 The game crashes when I get in the submarine from alex's caves mod and switch to third-person view.

**Version Information (please complete the following information):**
 - Minecraft [1.20.1]
 - Forge [47.2.20]
 - Mana and Artifice [3.0.0.10]
 - Alexscaves [1.1.4]
 - Curios [5.7.2]
 - Citadel [2.5.4]
 - Geckolib [4.4.2]

**Additional context**
[crash-2024-03-17_01.25.39-client.txt](https://github.com/Mithion/Mana-And-Artifice/files/14624880/crash-2024-03-17_01.25.39-client.txt)

**Comment by Mithion** [comment] 2024-03-20 23:23
Duplicate of #721

**Closed by Mithion** 2024-03-20 23:23 UTC
