### ISSUE TITLE
Light Pylon doesn't complete the Tier-up task

### ISSUE THREAD

**Issue by BriarThorn94** [Mithion/Mana-And-Artifice#1026] opened 2024-12-10 15:28 UTC
**Describe the bug**
Crafting the Light Pylon doesn't complete the task for crafting a Tier 2 Pylon in order to reach Tier 3.

**To Reproduce**
1. Craft the Light Pylon

**Expected behavior**
The task "Craft a Tier 2 Pylon" won't complete

**Version Information**
 - Mod Version: 3.1.0.1
 - Forge Version 1.20.1

**Additional context**
Auram Magica pack. Version 1.3.1

**Comment by ShelLuser** [comment] 2024-12-15 02:09
So, this bug got mentioned on Discord today. I got intriguied, looked into it and found both the cause and a solution. I'm gonna elaborate a bit to make sure this comment can be used by everyone (including Mith I hope; saving him some time perhaps), but I'll also add a summary at the bottom just in case (if you're in a hurry then check that).

**The problem**
Progression in MNA uses Minecraft's advancement system; this system is based on triggers & conditions. The involved advancement for this issue is "mna:tier_2/craft_t2_pylon", its trigger is "minecraft:inventory_changed" (aka: some item gets added or removed from a players inventory) and its condition... _that's_ where the problem is.

In MNA 1.20.1 3.1.0.1 the condition for this advancement only uses these pylons: haste, insight, leap and spider climbing, but not light.

**The solution**
The quickest fix is to give the player the required advancement, of course this requires access to commands (aka "cheating"). Even so, this command will give a player the proper progression => _**/advancement grant PlayerName only mna:tier_2/craft_t2_pylon**_, where "PlayerName" should be replaced with the name of the involved player.

Obviously this doesn't really work for a server where you'd have to monitor all your players to see if they really crafted a tier 2 pylon ;)

So a more permanent solution can be set up using a datapack in which you override the advancement with an updated one, see my attachment.

Now, I'm not gonna explain how to set up a datapack here, but if you have one set up then you need to place the attached JSON file in this datapack folder: "data\mna\advancements\tier_2\".  The attachment contains a copy of the original JSON file in which I simply added the extra pylon of light to the list of conditions.

Note: I attached a ZIP file because Github doesn't like JSON, just unzip it and you'll get the JSON file, which is simply a text file so you can easily use notepad or such to verify the file before using (which you should **always** do no matter what!).

**Summary**
- You can use this command as quickfix => _**/advancement grant PlayerName only mna:tier_2/craft_t2_pylon**_ (where "PlayerName" should be replaced with the name of the involved player).
- I attached an updated / "fixed" copy of "craft_t2_pylon.json" which is the advancement that handles this progression. If you set up a datapack you can place this in this datapack folder: "data\mna\advancements\tier_2\", that will override the original advancement, thus fixing the problem (note: players obviously need to re-craft the pylon for the new advancement to trigger).


[craft_t2_pylon.zip](https://github.com/user-attachments/files/18138580/craft_t2_pylon.zip)

**Comment by Mithion** [comment] 2024-12-31 17:14
This was resolved in 3.1.0.2

**Closed by Mithion** 2024-12-31 17:14 UTC
Labels: Fixed In Dev
