### ISSUE TITLE
Config Request Disable Faction fighting

### ISSUE THREAD

**Issue by litjohn50** [Mithion/Mana-And-Artifice#219] opened 2021-04-13 02:32 UTC
Faction fighting is cool and all, but there has been many times there FPS drops significantly effect the gameplay.

Example 1: Witch hunter's Targeting other faction mobs with arrows and potions.

Where a Witch hunter will spend the whole time until they die shooting arrows at a pixie

https://gyazo.com/4fa24c96697aa988b1e58d573182e3cf

The Amount of arrow entities spawned by these witch hunters in a short period of time. 

https://cdn.discordapp.com/attachments/356951809572470786/831349446411157564/unknown.png  <- with help of another mod to track the issue

Fps Dropping anywhere from around 5fps to 20fps from being within rendering area of those arrows. 

https://cdn.discordapp.com/attachments/356951809572470786/831353447243841546/unknown.png

This would be much obliged if you can take some time to have the config option toggleable. 

Thanks!

**Comment by Mithion** [comment] 2021-05-01 00:35
I'd rather make the arrows last less time in the ground as that seems to be the root cause.

**Comment by Mithion** [comment] 2021-06-23 03:59
This has been fixed in dev, and will go out with version 14.0.0.

**Closed by Mithion** 2021-06-23 03:59 UTC
Labels: Fixed In Dev, bug
