### ISSUE TITLE
Codex causes everything to disappear

### ISSUE THREAD

**Issue by CrystalDiamondia** [Mithion/Mana-And-Artifice#299] opened 2021-07-08 08:28 UTC
**Describe the bug**
Opening the Codex causes all of the text and item sprites in-game to disappear. This even affects the title screen.

**To Reproduce**
1. Get the Codex Arcana (I acquired it through the Akashic Tome given on spawn)
2. Use it
3. See error

**Expected behavior**
I expected to open the codex normally and start using the mod.

**Screenshots**
https://imgur.com/a/3ecD4Xd
I forgot to screenshot the item sprites disappearing, but I couldn't restart my game after this happened - it crashed on startup.

**Version Information (please complete the following information):**
 - Mod Version: 1.3.0.6
 - Forge Version: 36.1.31

**Additional context**
I'm using All The Mods 6 and Complementary Shaders.

Update: Disabling the mana GUI entirely fixes the bug.

**Comment by CrystalDiamondia** [comment] 2021-07-08 11:17
Update: I was able to restart the world, but it causes the UI to flash uncontrollably.
![obraz](https://user-images.githubusercontent.com/54674248/124912902-c9748800-dfee-11eb-8e1b-d47d27b9b78f.png)

**Comment by AtelierAmber** [comment] 2021-07-08 19:33
To add to this, this problem only happens when shaders are enabled. If shaders are enabled the problem does not happen even with optifine installed.

**Comment by Mithion** [comment] 2021-07-09 13:26
This is due to Xaero's minimap, it's a known conflict.  Only workaround at this point is to use a different minimap mod.

**Comment by Mithion** [comment] 2021-07-09 13:27
Closing as a duplicate of #231 (which is the same root issue).

**Closed by Mithion** 2021-07-09 13:27 UTC
Labels: Other Mod Issue
