### ISSUE TITLE
Witch And Spellbreaker Crash

### ISSUE THREAD

**Issue by UldisAlksnis** [Mithion/Mana-And-Artifice#201] opened 2021-03-23 15:41 UTC
Hello,
I am unsure if you support modpacks but I have posted this issue also on ATM6 github.

The server is running ATM6 1.5.5 with Quark_realistic world on Java 11
So far every error includes either mana-and-artifice witch or spellbreaker.

Spellbreaker:
https://pastebin.com/0Ps3tP3Z
https://pastebin.com/eLkX4J5T

Witch:
https://pastebin.com/9MsNfk92

**Comment by iarspider** [comment] 2021-03-23 16:40
Probably duplicate of #193

**Closed** 2021-03-28 14:17 UTC
