### ISSUE TITLE
Not Levelling from using spells

### ISSUE THREAD

**Issue by heater405** [Mithion/Mana-And-Artifice#232] opened 2021-05-05 05:24 UTC
I just made my first spell which was a touch break spell. I have been spamming it for quite some time (breaking coal blocks the spell is actually working) and I haven't gained any experience to level up. I am using the latest beta version released on 1.16.5

**Comment by LeoBeliik** [comment] 2021-05-06 14:24
I've noticed this too, to add more information, touch break spells don't consume mana, so I guess that's where the problem is, you also can't rote neither touch not break with this spell combination.
Tested it with forge 36.1.13 and M&A 1.3.0.6

**Comment by Mithion** [comment] 2021-05-06 14:47
This is a known issue with the Break component, I have it fixed in dev.  It'll go out with the next update!

**Comment by Mithion** [comment] 2021-06-23 03:59
This has been fixed in dev, and will go out with version 14.0.0.

**Closed by Mithion** 2021-06-23 03:59 UTC
Labels: Fixed In Dev, bug
