### ISSUE TITLE
Issues with deactivation rituals without completion.

### ISSUE THREAD

**Issue by Sidnatum0** [Mithion/Mana-And-Artifice#61] opened 2020-08-14 11:09 UTC
Right-click use of Purified Vinteum Dust on the center of the activated ritual, consumes it, and breaking runes had no effect.
Redrawing the runes in the same place and reactivating the ritual left the previous items flying unchanged.
(However, Shift + Right Click works as expected.)
![2020-08-14_13 46 46](https://user-images.githubusercontent.com/55444707/90243449-96099780-de37-11ea-8c8b-464efb20dfbf.png)
1.0.6-pre2

**Comment by Mithion** [comment] 2020-08-25 13:29
I'm having trouble understanding the issue - rituals aren't meant to be cancelled by breaking chalk blocks; its either shift right click with vinteum (which only works until you start the rituals main phase, after that it no longer works and breaking a rune will make it explode) or complete the ritual.  

What's the expectation here?

**Comment by Sidnatum0** [comment] 2020-08-26 02:23
1. The runes of the ritual are drawn. (In particular Ritual Of Arcana)
2. Right click with purified vinteum dust to activate the ritual.
3. Enchanted vellum is placed.
4. The items needed to create the spell appear.
5. If all items for the ritual are not placed, then another right click with purified vinteum dust will simply consume it.
6. It doesn't have to be this way. Purified vinteum dust should not be consumed and should not interact with the ritual until all the necessary items have been placed. Perhaps, in this case, a message should be displayed stating that the ritual is not completed.
(At the same time, the ritual seems to be restarted, but the runes remain purple, the required enchanted vellum disappears, and the rest of the required items continue to float.)

**Comment by Mithion** [comment] 2020-08-26 21:20
Ah, OK that makes so much more sense now.  Thanks for clarifying.

With the exception of the excess consumption of purified vinteum it's working as intended.  The items disappear because the correct item is in that place.  It's meant to help reduce visual clutter and help to identify an item that may be missing, especially with some of the more complex rituals.

I'll fix up the vinteum consumption issue for the next version though.

**Comment by Mithion** [comment] 2020-08-26 23:48
This has been fixed in 1.0.6-pre3.

**Closed by Mithion** 2020-08-26 23:48 UTC
Labels: bug
