### ISSUE TITLE
[1.18.1] Server crash: server tick takes too long and crashes checking for whether target already has a spell's effect applied

### ISSUE THREAD

**Issue by Febilian** [Mithion/Mana-And-Artifice#470] opened 2022-03-20 04:29 UTC
**Describe the bug**
I crashed a server by casting too many projectile frost spells at some distant hostile mobs, and it seems to reference a check for whether a spell's target is already afflicted with a spell's applied effects.

https://gist.github.com/Febilian/17455eb3e5a947f8ca004feb9559c464

I'm not 100% sure exactly how this was triggered, but I know it was related to me casting a great many spells very very quickly, probably so quickly that the entity was being hit by the spell so fast that whatever checks for whether a targeted entity already has an effect from a spell applied just... was unable to keep up somehow.

This doesn't happen consistently. I only noticed it when I was rapidly firing a LOT of my projectile frost damage spell at faraway enemies very quickly. I've been using this spell for a few days IRL now of constant play and haven't encountered the issue until now.

**To Reproduce**
1. Use a projectile frost spell modified with speed once rapidly against a lot of mobs. Like, nonstop casting it. Not sure if it makes a difference but I'm at 100% water affinity and am magic level 30 and this once again occurred on a server setting.
2. Hope that one of the times the spell hits a target, the problem occurs. I suspect it has to do with hitting an entity with a spell rapidly in a very short amount of time?

**Expected behavior**
For the game to not crash when using a survival-made spell against an entity.

**Version Information (please complete the following information):**
 - Mod Version: Mana and Artifice 1.7.0.5
 - Forge Version 39.1.2
 - Minecraft 1.18.1

**Additional context**
Other mods are installed and should be listed in the crash report. I doubt this is a mod conflict however.

**Comment by Mithion** [comment] 2022-05-04 13:53
TBH that looks like a JVM error to me, but I did refactor the system to use a more simple data structure in the hopes that it will mitigate the issue in the next release (1.18.1).

I wasn't able to recreate the issue at all unfortunately.  We'll need to see if the issue is in fact resolved in the next update.

**Comment by Mithion** [comment] 2022-06-11 18:42
Version 1.7.2.3 has been released, which resolves this issue.

**Closed by Mithion** 2022-06-11 18:42 UTC
Labels: Fixed In Dev
