### ISSUE TITLE
Loot Table ID is null

### ISSUE THREAD

**Issue by Alrena** [Mithion/Mana-And-Artifice#730] opened 2024-03-15 05:41 UTC
Server crashes when logging in, with the only apparent problem pointing to Mana and Artifice.

This is a custom mod pack, but it seems that there could be a problem with Barkling mobs, possibly that one of them died and couldn't give a loot table.

[crash-2024-03-14_22.29.03-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/14611318/crash-2024-03-14_22.29.03-server.txt)

**Comment by Darkmega18** [comment] 2024-03-15 08:46
I've had a couple of these over the last few hours very similar crashes, but all for different entities. One time, a floating ward, and another time some kind of zombie. At first I considered maybe apotheosis 1.20 backport from recent broke something, but all of them are pointing towards something in mana and artifice in some way shape or form. 

Although one also pointed to "Mii alliance" when I tried to remove mana and artifice. 
don't know if it's just more likely to occur due to your factions mobs fighting one another or what, but it wasn't happening the other day before I updated a bunch of mods today, including adding MnA due to a friend always wanting to try it and so I figured I'd give it a chance over something simpler...

[crash-2024-03-15_15.33.45-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/14612991/crash-2024-03-15_15.33.45-server.txt)
[crash-2024-03-15_15.29.55-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/14612992/crash-2024-03-15_15.29.55-server.txt)
[crash-2024-03-15_15.20.40-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/14612994/crash-2024-03-15_15.20.40-server.txt)
[crash-2024-03-15_19.38.13-server.txt](https://github.com/Mithion/Mana-And-Artifice/files/14612990/crash-2024-03-15_19.38.13-server.txt)

**Comment by Mithion** [comment] 2024-03-20 23:36
![image](https://github.com/Mithion/Mana-And-Artifice/assets/2482373/9ae5ad96-077e-41b0-90ec-38397ca7b128)

I would check this first, nothing in this crash report is screaming M&A as the cause.  I'll leave this open for a while in case there's more info that confirms it actually is M&A, but I'm strongly leaning towards it not being so at this time.

**Comment by Mithion** [comment] 2024-03-21 17:42
No worries.  I'm going to close this as resolved, then.

**Closed by Mithion** 2024-03-21 17:42 UTC
Labels: Other Mod Issue, Waiting on Information, 1.20
